# Generated by Django 3.1.7 on 2021-05-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='status',
        ),
    ]
