# Generated by Django 3.1.7 on 2021-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_accounts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromacc', models.IntegerField(max_length=10)),
                ('toacc', models.IntegerField(max_length=10)),
                ('amt', models.IntegerField(max_length=10)),
                ('trdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
